version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql

  backend:
    build: ./backend
    volumes:
      - ./backend:/adventext/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  webclient:
    build: ./webclient
    command: ["npm", "start"]
    volumes:
      - ./webclient:/adventext/webclient
    ports:
      - "3000:3000"
      - "35729:35729"

volumes:
  db_volume: {}